# Settings for local testing
server.port: 8088

server:
  error:
    include-message: always
    include-exception: false
    include-stacktrace: on_param

  compression:
    enabled: true
    min-response-size: 2038
    mime-types: application/json, application/ld+json, application/xml, text/html, text/xml, text/plain
  forward-headers-strategy: framework # this is to make sure SpringDoc uses https when used over https connections

management:
  endpoints:
    web:
      exposure:
        include: info, health

  info:
    env:
      enabled: true

  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

# Creates a redirect from /console to /swagger-ui/index.html
springdoc:
  swagger-ui:
    path: /console
  # Don't include Error controller in API commons
  paths-to-exclude: /error

