# Settings for local testing
server.port: 8085

server:
  error:
    include-message: always
    include-exception: false
    include-stacktrace: on_param

  compression:
    enabled: true
    mime-types: application/json, application/ld+json, application/xml, text/html, text/xml, text/plain
    min-response-size: 2048