apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommend-api-deployment
spec:
  # selector.matchLabels is provided via Kustomize
  template:
    spec:
      containers:
        - name: recommend-api
          image: europeana/recommend-api
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
            initialDelaySeconds: 70
            periodSeconds: 20
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
            initialDelaySeconds: 70
            periodSeconds: 20
          volumeMounts:
            - name: secret
              mountPath: "/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/recommend.user.properties"
              readOnly: true
              subPath: recommend.user.properties
      volumes:
        - name: secret
          secret:
            secretName: recommend-api-secret