resources:
  - deployment.yaml

commonLabels:
  app: recommend-api

# expects files to be in the same directory
secretGenerator:
  - name: recommend-api-secret
    files:
      - recommend.user.properties
