resources:
  - deployment.yaml

labels:
  - includeSelectors: true
    pairs:
      app: recommend-api

# expects files to be in the same directory
secretGenerator:
  - name: recommend-api-secret
    files:
      - recommend.user.properties
